<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Created At' => '创建时间',
    'Description' => '描述',
    'Draft' => '草稿',
    'ID' => 'ID',
    'Published' => '发布',
    'Published At' => '发布时间',
    'Rejected' => '拒绝',
    'Review' => '待审核',
    'Slug' => '标识',
    'Status' => '状态',
    'Title' => '标题',
    'Updated At' => '更新时间',
    'Url' => 'Url地址',
    'User ID' => '用户ID',
    'Views' => '查看次数',
];
